smu.ATTR_MEAS_RANGE_AUTO = nil
smu.ATTR_MEAS_RANGE_HIGH = nil
smu.ATTR_MEAS_RANGE_LOW = nil
smu.ATTR_MEAS_RANGE_REBOUND = nil
smu.ATTR_MEAS_AUTO_ZERO = nil
smu.ATTR_MEAS_COUNT = nil
smu.ATTR_MEAS_DIGITS = nil
smu.ATTR_MEAS_NPLC = nil
smu.ATTR_MEAS_OFFSET_COMP = nil
smu.ATTR_MEAS_RANGE = nil
smu.ATTR_MEAS_REL_ENABLE = nil
smu.ATTR_MEAS_REL_LEVEL = nil
smu.ATTR_MEAS_SENSE = nil
smu.ATTR_MEAS_UNIT = nil
smu.ATTR_MEAS_USER_DELAY_1 = nil
smu.ATTR_MEAS_USER_DELAY_2 = nil
smu.ATTR_MEAS_USER_DELAY_3 = nil
smu.ATTR_MEAS_USER_DELAY_4 = nil
smu.ATTR_MEAS_USER_DELAY_5 = nil
smu.ATTR_MEAS_FILTER_COUNT = nil
smu.ATTR_MEAS_FILTER_ENABLE = nil
smu.ATTR_MEAS_FILTER_TYPE = nil
smu.ATTR_MEAS_MATH_ENABLE = nil
smu.ATTR_MEAS_MATH_MXB_BF = nil
smu.ATTR_MEAS_MATH_MXB_MF = nil
smu.ATTR_MEAS_MATH_FORMAT = nil
smu.ATTR_MEAS_MATH_PERCENT = nil
smu.ATTR_MEAS_LIMIT_AUDIBLE_1 = nil
smu.ATTR_MEAS_LIMIT_AUTO_CLEAR_1 = nil
smu.ATTR_MEAS_LIMIT_ENABLE_1 = nil
smu.ATTR_MEAS_LIMIT_FAIL_1 = nil
smu.ATTR_MEAS_LIMIT_HIGH_1 = nil
smu.ATTR_MEAS_LIMIT_LOW_1 = nil
smu.ATTR_MEAS_LIMIT_AUDIBLE_2 = nil
smu.ATTR_MEAS_LIMIT_AUTO_CLEAR_2 = nil
smu.ATTR_MEAS_LIMIT_ENABLE_2 = nil
smu.ATTR_MEAS_LIMIT_FAIL_2 = nil
smu.ATTR_MEAS_LIMIT_HIGH_2 = nil
smu.ATTR_MEAS_LIMIT_LOW_2 = nil

---@alias smuMeasuresetFunctionattribute
---|`.ATTR_MEAS_RANGE_AUTO`
---|`.ATTR_MEAS_RANGE_HIGH`
---|`.ATTR_MEAS_RANGE_LOW`
---|`.ATTR_MEAS_RANGE_REBOUND`
---|`.ATTR_MEAS_AUTO_ZERO`
---|`.ATTR_MEAS_COUNT`
---|`.ATTR_MEAS_DIGITS`
---|`.ATTR_MEAS_NPLC`
---|`.ATTR_MEAS_OFFSET_COMP`
---|`.ATTR_MEAS_RANGE`
---|`.ATTR_MEAS_REL_ENABLE`
---|`.ATTR_MEAS_REL_LEVEL`
---|`.ATTR_MEAS_SENSE`
---|`.ATTR_MEAS_UNIT`
---|`.ATTR_MEAS_USER_DELAY_1`
---|`.ATTR_MEAS_USER_DELAY_2`
---|`.ATTR_MEAS_USER_DELAY_3`
---|`.ATTR_MEAS_USER_DELAY_4`
---|`.ATTR_MEAS_USER_DELAY_5`
---|`.ATTR_MEAS_FILTER_COUNT`
---|`.ATTR_MEAS_FILTER_ENABLE`
---|`.ATTR_MEAS_FILTER_TYPE`
---|`.ATTR_MEAS_MATH_ENABLE`
---|`.ATTR_MEAS_MATH_MXB_BF`
---|`.ATTR_MEAS_MATH_MXB_MF`
---|`.ATTR_MEAS_MATH_FORMAT`
---|`.ATTR_MEAS_MATH_PERCENT`
---|`.ATTR_MEAS_LIMIT_AUDIBLE_1`
---|`.ATTR_MEAS_LIMIT_AUTO_CLEAR_1`
---|`.ATTR_MEAS_LIMIT_ENABLE_1`
---|`.ATTR_MEAS_LIMIT_FAIL_1`
---|`.ATTR_MEAS_LIMIT_HIGH_1`
---|`.ATTR_MEAS_LIMIT_LOW_1`
---|`.ATTR_MEAS_LIMIT_AUDIBLE_2`
---|`.ATTR_MEAS_LIMIT_AUTO_CLEAR_2`
---|`.ATTR_MEAS_LIMIT_ENABLE_2`
---|`.ATTR_MEAS_LIMIT_FAIL_2`
---|`.ATTR_MEAS_LIMIT_HIGH_2`
---|`.ATTR_MEAS_LIMIT_LOW_2`