image:
  name: git.keithley.com:5050/trebuchet/teaspoon/teaspoon-build:latest
  entrypoint: [""]

include:
  # https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml


variables:
  NODE_EXTRA_CA_CERTS: "/etc/ssl/certs/ca-certificates.crt"

stages:
  - package
  - deploy

package:
  stage: package
  script:
    - cd keithley_instrument_libraries
    - npm pack
  artifacts:
    name: npm-package
    paths:
      - ./keithley_instrument_libraries/*.tgz

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - package
  script:
    - cd keithley_instrument_libraries
    - npm config set @trebuchet:registry "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm config set -- "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
    - npm publish
